defaults:
  - default
  - _self_

agent_type: on_policy
network_class: actor_critic_with_state_value
encoder: temporal_only
temporal_model_type: identity
image_processor_type: simple_cnn
batch_size: 16
learning_rate: 1e-5
buffer_capacity: 2048
policy_type: beta
on_policy_epoch: 5
disable_state_predictor: 1
detach_actor: 0
critic_loss_weight: 2.0
max_grad_norm: 0.5
separate_critic: 1
