program: scripts/train.py
method: grid
parameters:
  use_prompt:
    values: [0, 1]
  agent_type:
    values: [off_policy, streaming]
  seed:
    values: [0, 1, 2, 3, 4]
command:
  - ${env}
  - uv
  - run
  - python
  - ${program}
  - agent=vlm_streaming
  - env=gui
  - ${args_no_hyphens}
