defaults:
  - default

exp_name: baseline
env_id: TrackingSquare-v0
agent_type: off_policy
network_class: vlm_actor_critic_with_action_value
step_limit: 50_000
batch_size: 16
learning_rate: 1e-5
disable_state_predictor: 1
state_mode: expert
use_lora: 1
