defaults:
  - default
  - _self_

exp_name: baseline
env_id: TrackingSquare-v0
agent_type: streaming
network_class: vlm_actor_critic_with_action_value
step_limit: 50_000
batch_size: 16
learning_rate: 1e-5
disable_state_predictor: 1
use_lora: 1
use_done: 0
prediction_type: data  # "velocity" or "data" (x-prediction)
gamma: 0.2
et_lambda: 0.2
state_mode: projection
