program: scripts/train.py
method: bayes
metric:
  name: best_recent_average_score
  goal: maximize
parameters:
  learning_rate:
    min: 1e-6
    max: 1e-4
    distribution: log_uniform_values
  gamma:
    min: 0.0
    max: 1.0
    distribution: uniform
  use_lora:
    values: [0, 1]
  use_done:
    values: [0, 1]
  prediction_type:
    values: ["velocity", "data"]
  max_step_count:
    min: 10
    max: 200
    distribution: int_uniform
command:
  - ${env}
  - uv
  - run
  - python
  - ${program}
  - --config-name
  - gui_env
  - agent_type=streaming
  - ${args_no_hyphens}
