program: scripts/train.py
method: bayes
metric:
  name: total_average_score
  goal: maximize
parameters:
  learning_rate:
    min: 1e-7
    max: 1e-5
    distribution: log_uniform_values
  gamma:
    min: 0.0
    max: 1.0
    distribution: uniform
  et_lambda:
    min: 0.0
    max: 1.0
    distribution: uniform
  denoising_time:
    min: 0.5
    max: 1.0
    distribution: uniform
  state_out_dim:
    min: 1
    max: 16
    distribution: int_uniform
  num_state_queries:
    min: 1
    max: 219
    distribution: int_uniform
command:
  - ${env}
  - uv
  - run
  - python
  - ${program}
  - agent=vlm_streaming
  - env=car_racing
  - step_limit=100_000
  - ${args_no_hyphens}
