# @package _global_
agent_type: on_policy
network_class: actor_critic_with_state_value
encoder: temporal_only
temporal_model_type: identity
image_processor_type: simple_cnn
policy_type: beta
batch_size: 16
learning_rate: 1e-5
buffer_capacity: 2048
on_policy_epoch: 10
clip_param_policy: 0.2
clip_param_value: 0.2
